env:
  es6: true
  node: true
  browser: true
extends:
  - "eslint:recommended"
  - prettier
parserOptions:
  ecmaVersion: 2018
  sourceType: module
overrides:
  - files: ["*.ts"]
    extends:
      - "eslint:recommended"
      - "plugin:@typescript-eslint/recommended"
      - "plugin:@typescript-eslint/recommended-requiring-type-checking"
      - "prettier/@typescript-eslint"
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: ["./tsconfig.json"]
    plugins: ["@typescript-eslint"]
    rules:
      no-var: 0
      "@typescript-eslint/restrict-template-expressions": off
      "@typescript-eslint/ban-types": off
      "@typescript-eslint/no-empty-interface": off
      "@typescript-eslint/no-explicit-any": off
      "@typescript-eslint/no-unsafe-call": off
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/no-unsafe-assignment": off
      "@typescript-eslint/restrict-plus-operands": off
      "@typescript-eslint/no-unsafe-return": off
      "@typescript-eslint/no-var-requires": off
      "@typescript-eslint/no-empty-function": off
      "@typescript-eslint/no-this-alias": off
      "@typescript-eslint/no-implied-eval": off
      no-invalid-this: off
rules:
  block-scoped-var: error
  callback-return: error
  complexity: [error, 17]
  curly: [error, multi-line, consistent]
  dot-location: [error, property]
  dot-notation: error
  eqeqeq: [error, smart]
  id-match: error
  linebreak-style: [error, unix]
  new-cap: error
  no-console: [error, allow: [warn, error]]
  no-debugger: error
  no-duplicate-imports: error
  no-else-return: error
  no-eq-null: error
  no-eval: error
  no-fallthrough: error
  no-invalid-this: error
  no-new-wrappers: error
  no-path-concat: error
  no-redeclare: error
  no-return-assign: error
  no-sequences: error
  no-shadow: warn
  no-template-curly-in-string: error
  no-trailing-spaces: error
  no-undef-init: error
  no-use-before-define: [error, nofunc]
  prefer-arrow-callback: error
  prefer-const: error
  radix: error
  semi: 0
  valid-jsdoc: [error, requireReturn: false]
  no-control-regex: 0
  no-useless-escape: error
  no-void: error
  # no-var: error
